## LOGISTIC REGRESSION

In [1]:
#  Import Libraries
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression     # classfication model
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import accuracy_score,f1_score #model evaluation for classfication 
import joblib # To save the model

In [2]:
# Data loading
df=pd.read_csv("Churn_Modelling.xls")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# droping useless columns 
df.drop(columns=["RowNumber","CustomerId","Surname","Geography"],inplace=True)

In [4]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# handling categorical columns 
df["Gender"]=df["Gender"].map({"Female":0,"Male":1})

In [6]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,42,2,0.00,1,1,1,101348.88,1
1,608,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,39,1,0.00,2,0,0,93826.63,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0

In [7]:
# feature selection
x=df.drop(columns=["Exited"])
y=df["Exited"]

In [8]:
# data splitting 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
# model selection - comparison
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# 3 models to define
log_model = LogisticRegression(max_iter=10000)   # logistic regression for simple accuracy
rf_model = RandomForestClassifier(random_state=42)   # Random forest for medium accuracy
xgb_model = XGBClassifier(eval_metric='logloss', random_state=42)  # for best accuracy

# Best model select - XGBoost
model = xgb_model

# model train
model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [10]:
# model evaluation 
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)

0.848

In [11]:
# traning data 
y_pred_train=model.predict(x_train)
accuracy_score(y_train,y_pred_train)

0.9545

# WITH SCALING

In [12]:
# model traning on scaled data 
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)

x_test_scaled=scaler.transform(x_test)      # not fit and transform on test data to avoid data leakage

In [13]:
# model traning o scaled data 
model.fit(x_train_scaled,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [14]:
# model evaluation on test data 
y_pred=model.predict(x_test_scaled)
accuracy_score(y_test,y_pred)

0.848

# PREDICTIVE MODEL

In [16]:
# CreditScore	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary 
print("Enter Customer Details for Prediction:-----")
CreditScore=int(input("Enter CreditScore: "))
Gender=int(input("Enter Gender (Female:0, Male:1): "))
Age=int(input("Enter Age: "))
Tenure=int(input("Enter Tenure: "))
Balance=float(input("Enter Balance: "))
NumOfProducts=int(input("Enter NumOfProducts: "))
HasCrCard=int(input("Enter HasCrCard: "))
IsActiveMember=int(input("Enter IsActiveMember: "))
EstimatedSalary=float(input("Enter EstimatedSalary: "))

# User input to scale 
user_data=[[CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary]]
user_data_scaled = scaler.transform(user_data)

pred = model.predict(user_data_scaled)

if pred[0]==1:
    print("Customer will EXIT the bank")
else:
    print("Customer will STAY")

Enter Customer Details for Prediction:-----

Enter CreditScore:  600
Enter Gender (Female:0, Male:1):  0
Enter Age:  45
Enter Tenure:  5
Enter Balance:  100000
Enter NumOfProducts:  1
Enter HasCrCard:  1
Enter IsActiveMember:  10
Enter EstimatedSalary:  500000

Customer will STAY

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [18]:
# To save the model
import joblib
joblib.dump(model, "chrun_model.pkl")
joblib.dump(scaler, "scaler.pkl")
print("Saved!")

Saved!