In [1]:
# Import libraries 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder  # encoding techinique
from sklearn.tree import DecisionTreeRegressor  # decision tree 
from sklearn.ensemble import RandomForestRegressor # random forest
from sklearn.metrics import r2_score

In [2]:
# Data loading 
df=pd.read_csv("House_price_dataset.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [3]:
# data preprocessing   - for data cleaning 
# to check null values 
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [4]:
# to permamnetly remove duplicated values
df.drop_duplicates(inplace=True)

In [5]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [6]:
# To counts the values to handling categorial data 
df["date"].value_counts()

date
2014-06-23 00:00:00    142
2014-06-25 00:00:00    131
2014-06-26 00:00:00    131
2014-07-08 00:00:00    127
2014-07-09 00:00:00    121
                      ...
2014-06-07 00:00:00      4
2014-07-06 00:00:00      3
2014-07-04 00:00:00      2
2014-05-11 00:00:00      2
2014-05-17 00:00:00      1
Name: count, Length: 70, dtype: int64

In [7]:
df["street"].value_counts()

street
2520 Mulberry Walk NE     4
2500 Mulberry Walk NE     3
9413 34th Ave SW          2
6008 8th Ave NE           2
11034 NE 26th Pl          2
                         ..
1404 Broadmoor Dr E       1
3249 E Ames Lake Dr NE    1
6032 35th Ave NE          1
1006 NE Ravenna Blvd      1
18717 SE 258th St         1
Name: count, Length: 4525, dtype: int64

In [8]:
df["city"].value_counts()

city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Issaquah                187
Kirkland                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
SeaTac                   29
Tukwila                  29
Vashon                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Clyde Hill               11
Medina                   11
Fall City                11
Black Diamond             9
Ravensdale                7
Pacific                   6
Algona                    5
Yarrow Point              4
Skykomish                 3
Preston                   2
Milton                    2
Inglewood-Finn Hill       1
Snoqualmie Pass           1
Beaux Arts Village        1
Name: count, dtype: int64

In [9]:
df["statezip"].value_counts()

statezip
WA 98103    148
WA 98052    135
WA 98117    132
WA 98115    130
WA 98006    110
           ...
WA 98047      6
WA 98288      3
WA 98050      2
WA 98354      2
WA 98068      1
Name: count, Length: 77, dtype: int64

In [10]:
df["country"].value_counts()

country
USA    4600
Name: count, dtype: int64

In [11]:
# handling categorical column - 
le1 = LabelEncoder()
le2 = LabelEncoder()
df["encoded_city"] = le1.fit_transform(df["city"])
df["encoded_statezip"] = le2.fit_transform(df["statezip"])

In [21]:
# then drop encoded columns
df = df.drop(columns=['encoded_date','encoded_street','encoded_country','date','street','country'], errors='ignore')

In [22]:
# To check how many columns are left
print(df.columns.tolist())
df.head()

['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'encoded_city', 'encoded_statezip']

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,encoded_city,encoded_statezip
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,36,62
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,35,58
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,18,26
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,3,7
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,31,31

In [23]:
# feature selection for model 
x=df.drop(columns=["price"])
y=df["price"]

In [24]:
# data splitting 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
# MODEL ACCURACY - All models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# 1. Linear Regression
model = LinearRegression()
model.fit(x_train, y_train)
print("Linear Regression TRAIN:", r2_score(y_train, model.predict(x_train)))
print("Linear Regression TEST:", r2_score(y_test, model.predict(x_test)))

print("--------------------")

# 2. Decision Tree - max_depth 12 
tree = DecisionTreeRegressor(max_depth=12, random_state=42)
tree.fit(x_train, y_train)
print("Decision Tree TRAIN:", r2_score(y_train, tree.predict(x_train)))
print("Decision Tree TEST:", r2_score(y_test, tree.predict(x_test)))

print("--------------------")

# 3. Random Forest - FINAL BEST MODEL
random = RandomForestRegressor(n_estimators=200, max_depth=12, random_state=42)
random.fit(x_train, y_train)
print("Random Forest TRAIN:", r2_score(y_train, random.predict(x_train)))
print("Random Forest TEST:", r2_score(y_test, random.predict(x_test)))

Linear Regression TRAIN: 0.5489929900837383
Linear Regression TEST: 0.033276429849472544
--------------------
Decision Tree TRAIN: 0.9295131819973376
Decision Tree TEST: 0.011862963381194747
--------------------
Random Forest TRAIN: 0.9126477842133174
Random Forest TEST: 0.04342845065808687

## PREDECTIVE MODEL ==

In [26]:
## BY RANDOM FOREST REGRESSION --->

In [26]:
# bedrooms	bathrooms	sqft_living	sqft_lot	floors	waterfront	view	condition	sqft_above	sqft_basement	yr_built	yr_renovated	street	city	statezip	country
print("Enter the House Price Prediction----")
bedrooms=int(input("Enter no. of bedrooms -->:"))
bathrooms=float(input("Enter the no. of bathrooms -->:"))
sqft_living=int(input("Enter sqft_living of house --> :"))
sqft_lot=int(input("Enter sqft_lot of house --> :"))
floors=float(input("Enter the floors of house -->:"))
waterfront=int(input("Enter waterfront of house (0 for NO, 1 for yes):"))
view=int(input("Enter the view of house (0-4):"))
condition=int(input("Enter the condition of house (1-5):"))
sqft_above=int(input("Enter the sqft_above --> :"))
sqft_basement=int(input("Enter the sqft_basement -->:"))
yr_built=int(input("Enter the yr_built (e.g., 1995):"))
yr_renovated=int(input("Enter the yr_renovated (0 if never):"))
encoded_city=int(input("Enter city code (0-44):"))
encoded_statezip=int(input("Enter statezip code (0-69):"))

pred = random.predict([[bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,encoded_city,encoded_statezip]])
print("Selling price of house is:", pred[0])

Enter the House Price Prediction----

Enter no. of bedrooms -->: 3
Enter the no. of bathrooms -->: 2
Enter sqft_living of house --> : 1800
Enter sqft_lot of house --> : 6000
Enter the floors of house -->: 1
Enter waterfront of house (0 for NO, 1 for yes): 0
Enter the view of house (0-4): 0
Enter the condition of house (1-5): 3
Enter the sqft_above --> : 1500
Enter the sqft_basement -->: 300
Enter the yr_built (e.g., 1995): 2000
Enter the yr_renovated (0 if never): 0
Enter city code (0-44): 10
Enter statezip code (0-69): 20

Selling price of house is: 276883.18962206936

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [27]:
# To save the model 
import joblib

# for best model = random ...
joblib.dump(random, "house_price_model.pkl")
joblib.dump(le1, "city_encoder.pkl")      # city and satezip are not in the model that's why we cannot them ...
joblib.dump(le2, "statezip_encoder.pkl")

print("Saved!")

Saved!