In [21]:
# Import libraries
import pandas as pd  # data preprocessing
from sklearn.model_selection import train_test_split  # for data splitting
from sklearn.linear_model import LinearRegression  # regression model 
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder  # encoding techinique
from sklearn.metrics import r2_score  # model evaluation

In [10]:
# data loading 
df=pd.read_csv("laptop_data_cleaned.csv")
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac

In [11]:
print(df.columns.tolist())
print(df.head(2))

['Company', 'TypeName', 'Ram', 'Weight', 'Price', 'TouchScreen', 'Ips', 'Ppi', 'Cpu_brand', 'HDD', 'SSD', 'Gpu_brand', 'Os']
  Company   TypeName  Ram  Weight      Price  TouchScreen  Ips         Ppi  \
0   Apple  Ultrabook    8    1.37  11.175755            0    1  226.983005
1   Apple  Ultrabook    8    1.34  10.776777            0    0  127.677940

       Cpu_brand  HDD  SSD Gpu_brand   Os
0  Intel Core i5    0  128     Intel  Mac
1  Intel Core i5    0    0     Intel  Mac

In [3]:
# check null values 
df.isnull().sum()

Company        0
TypeName       0
Ram            0
Weight         0
Price          0
TouchScreen    0
Ips            0
Ppi            0
Cpu_brand      0
HDD            0
SSD            0
Gpu_brand      0
Os             0
dtype: int64

In [4]:
# to permanentely remove duplicate value
df.drop_duplicates(inplace=True)

In [5]:
# To check duplicates value are remove or not 
df.duplicated().sum()

np.int64(0)

In [6]:
# fiiling the null values 
df["Ram"]=df["Ram"].fillna(df["Ram"].mean())
df["HDD"]=df["HDD"].fillna(df["HDD"].mean())
df["SSD"]=df["SSD"].fillna(df["SSD"].median())

In [7]:
# To drop the useless column 
df.drop(columns=["Company","TypeName","Cpu_brand"], inplace=True)

In [12]:
# handling categorical  column
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()
le4 = LabelEncoder()
le5 = LabelEncoder()

df["encoded_Company"] = le1.fit_transform(df["Company"])
df["encoded_TypeName"] = le2.fit_transform(df["TypeName"])
df["encoded_Cpu_brand"] = le3.fit_transform(df["Cpu_brand"])
df["encoded_Gpu_brand"] = le4.fit_transform(df["Gpu_brand"])
df["encoded_Os"] = le5.fit_transform(df["Os"])

In [13]:
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os,encoded_Company,encoded_TypeName,encoded_Cpu_brand,encoded_Gpu_brand,encoded_Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac,1,4,2,1,0
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac,1,4,2,1,0
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others,7,3,2,1,1
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac,1,4,3,0,0
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac,1,4,2,1,0

In [14]:
# drop original column
df.drop(columns=["Company","TypeName","Cpu_brand","Gpu_brand","Os"],inplace=True)

In [15]:
df.head()

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD,encoded_Company,encoded_TypeName,encoded_Cpu_brand,encoded_Gpu_brand,encoded_Os
0,8,1.37,11.175755,0,1,226.983005,0,128,1,4,2,1,0
1,8,1.34,10.776777,0,0,127.677940,0,0,1,4,2,1,0
2,8,1.86,10.329931,0,0,141.211998,0,256,7,3,2,1,1
3,16,1.83,11.814476,0,1,220.534624,0,512,1,4,3,0,0
4,8,1.37,11.473101,0,1,226.983005,0,256,1,4,2,1,0

In [16]:
# feature selection for model 
x=df.drop(columns=["Price"])
y=df["Price"]

In [17]:
# data splitting
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
# model selection  - using Random forest get good accuracy
model = RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1)
model.fit(x_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [23]:
# to check Acurracy both train and test data 
y_pred = model.predict(x_test)
y_pred2 = model.predict(x_train)

print("Test R2:", r2_score(y_test, y_pred))
print("Train R2:", r2_score(y_train, y_pred2))

Test R2: 0.8803714019799821
Train R2: 0.9788716064184075

## PREDECTIVE MODEL

In [26]:
# Ram	Weight	TouchScreen	Ips	Ppi	HDD	SSD	encoded_Company	encoded_TypeName	encoded_Cpu_brand	encoded_Gpu_brand  encoded_Os
Ram = int(input("Enter Ram: "))
Weight = float(input("Enter Weight: "))
TouchScreen = int(input("TouchScreen No:0 Yes:1 : "))
Ips = int(input("Ips No:0 Yes:1 : "))
Ppi = float(input("Enter Ppi: "))
HDD = int(input("Enter HDD: "))
SSD = int(input("Enter SSD: "))
Company = int(input("Enter Company code - Apple:1 HP:7 etc: "))
TypeName = int(input("Enter TypeName code - Ultrabook:4 Notebook:3 etc: "))
Cpu_brand = int(input("Enter Cpu code: "))
Gpu_brand = int(input("Enter Gpu code: "))
Os = int(input("Enter Os code: "))

# ORDER MUST BE SAME AS X
import numpy as np
pred_log = model.predict([[Ram, Weight, TouchScreen, Ips, Ppi, HDD, SSD, Company, TypeName, Cpu_brand, Gpu_brand, Os]])
real_price = np.exp(pred_log[0])

print(f"Selling Price is: Rs. {real_price:.0f}")

Enter Ram:  8
Enter Weight:  1.5
TouchScreen No:0 Yes:1 :  0
Ips No:0 Yes:1 :  1
Enter Ppi:  220
Enter HDD:  0
Enter SSD:  512
Enter Company code - Apple:1 HP:7 etc:  7
Enter TypeName code - Ultrabook:4 Notebook:3 etc:  3
Enter Cpu code:  2
Enter Gpu code:  2
Enter Os code:  2

Selling Price is: Rs. 74395

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [27]:
import joblib

# 1. Model save
joblib.dump(model, "laptop_price_model.pkl")

# 2.save the encoder data 
joblib.dump(le1, "le_company.pkl")
joblib.dump(le2, "le_typename.pkl")
joblib.dump(le3, "le_cpu.pkl")
joblib.dump(le4, "le_gpu.pkl")
joblib.dump(le5, "le_os.pkl")

print("Model saved!")

Model saved!

In [28]:
# model saving 
import joblib
model = joblib.load("laptop_price_model.pkl")