In [1]:
# import libraries 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder  # encoding techinique
from sklearn.tree import DecisionTreeRegressor  # decision tree 
from sklearn.ensemble import RandomForestRegressor # random forest
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv(r"C:\Users\Admin\Downloads\House_price_dataset.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [3]:
# data preprocessing
# to check null values 
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [4]:
# to permamnetly remove duplicated values
df.drop_duplicates(inplace=True)

In [5]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [6]:
df["date"].value_counts()

date
2014-06-23 00:00:00    142
2014-06-25 00:00:00    131
2014-06-26 00:00:00    131
2014-07-08 00:00:00    127
2014-07-09 00:00:00    121
                      ...
2014-06-07 00:00:00      4
2014-07-06 00:00:00      3
2014-07-04 00:00:00      2
2014-05-11 00:00:00      2
2014-05-17 00:00:00      1
Name: count, Length: 70, dtype: int64

In [7]:
df["street"].value_counts()

street
2520 Mulberry Walk NE     4
2500 Mulberry Walk NE     3
9413 34th Ave SW          2
6008 8th Ave NE           2
11034 NE 26th Pl          2
                         ..
1404 Broadmoor Dr E       1
3249 E Ames Lake Dr NE    1
6032 35th Ave NE          1
1006 NE Ravenna Blvd      1
18717 SE 258th St         1
Name: count, Length: 4525, dtype: int64

In [8]:
df["city"].value_counts()

city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Issaquah                187
Kirkland                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
SeaTac                   29
Tukwila                  29
Vashon                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Clyde Hill               11
Medina                   11
Fall City                11
Black Diamond             9
Ravensdale                7
Pacific                   6
Algona                    5
Yarrow Point              4
Skykomish                 3
Preston                   2
Milton                    2
Inglewood-Finn Hill       1
Snoqualmie Pass           1
Beaux Arts Village        1
Name: count, dtype: int64

In [9]:
df["statezip"].value_counts()

statezip
WA 98103    148
WA 98052    135
WA 98117    132
WA 98115    130
WA 98006    110
           ...
WA 98047      6
WA 98288      3
WA 98050      2
WA 98354      2
WA 98068      1
Name: count, Length: 77, dtype: int64

In [10]:
df["country"].value_counts()

country
USA    4600
Name: count, dtype: int64

In [11]:
# handling categorical  column
label=LabelEncoder()     # initializing label model
df["encoded_date"]=label.fit_transform(df["date"])


df["encoded_street"]=label.fit_transform(df["street"])

df["encoded_city"]=label.fit_transform(df["city"])

df["encoded_statezip"]=label.fit_transform(df["statezip"])

df["encoded_country"]=label.fit_transform(df["country"])

In [12]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,yr_renovated,street,city,statezip,country,encoded_date,encoded_street,encoded_city,encoded_statezip,encoded_country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,...,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA,0,1522,36,62,0
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,...,0,709 W Blaine St,Seattle,WA 98119,USA,0,3899,35,58,0
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,...,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA,0,2291,18,26,0
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,...,0,857 170th Pl NE,Bellevue,WA 98008,USA,0,4263,3,7,0
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,...,1992,9105 170th Ave NE,Redmond,WA 98052,USA,0,4352,31,31,0

In [13]:
# drop original column
df.drop(columns=["date","street","city","statezip","country"],inplace=True)

In [14]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,encoded_date,encoded_street,encoded_city,encoded_statezip,encoded_country
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,0,1522,36,62,0
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,0,3899,35,58,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,0,2291,18,26,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,0,4263,3,7,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,0,4352,31,31,0

In [15]:
# feature selection for model 
x=df.drop(columns=["price"])
y=df["price"]
x

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,encoded_date,encoded_street,encoded_city,encoded_statezip,encoded_country
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,0,1522,36,62,0
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,0,3899,35,58,0
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,0,2291,18,26,0
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,0,4263,3,7,0
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,0,4352,31,31,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,68,3447,35,62,0
4596,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,68,960,3,6,0
4597,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,68,4033,32,37,0
4598,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,69,3498,35,71,0
4599,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,69,1514,9,26,0

In [16]:
# data splitting 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
# model selection
model=LinearRegression()    # model initialize

# model train
model.fit(x_train,y_train)

LinearRegression()

In [18]:
# model testing 
y_pred=model.predict(x_test)
y_pred

array([ 316064.67583707,  315217.37023824, 1071220.92321232,
        560198.39177532,  385891.77756424,  585752.12027587,
        455468.77878566,  421234.15540833,  501295.50814066,
        550373.79077906,  707534.66290162,  446770.3642239 ,
        805525.98535728,  437462.57262959,  262607.36645773,
        702552.27845136,  634833.47334656,  524661.30581238,
       1042919.89414865,  861748.32664928, 1397390.91377467,
        596089.72453353,  637328.39258776,  472566.32203953,
        158096.21372234,  214030.64213788,  632865.50947017,
        898640.22803959,  282894.68992549,  976561.53885044,
       1874088.59194409,  511705.03626165, 1248989.11636979,
        454767.56089373,  203163.24342159,  356490.43443371,
        802570.84754053,  947506.99636453,  254147.21404169,
        535715.1506543 ,  433558.16773853,  262025.12759398,
        390920.38202352,  379313.96502745,  233996.89217765,
        307499.72585329,  472170.21992536,  584822.60703775,
        845555.82052021,  476298.58737005, 1199848.40359144,
        390707.31926595,  472175.90929801,  669313.69649966,
        303065.97911673,  372971.77262332,  953014.84207003,
        800014.94742356,  998395.44963488,  317250.38186854,
        580855.66332044,  937605.7542935 ,  218835.82454745,
        915315.6716466 ,  798762.22942184,  552180.16126713,
        662732.79341411,  603396.07460067,  334119.78775564,
        302787.54118089, 1027545.88377317,  403852.77966143,
        386587.42547131,  889076.84202266,  348666.94567085,
        764976.30341206,  544803.25506481,  780739.0402214 ,
        387071.35168391,  217539.82752105,  586754.86157209,
        313193.71302035,  503251.3083113 ,  859458.62442832,
        404779.50575525,  250852.19442742,  426055.74668947,
        568892.55620919,  900277.98982039,  348534.46891659,
        886464.36255487,  305118.42775953,  286703.09240325,
        470193.25143971,  668150.43343727, 1126074.45951052,
        719693.09946743,  731407.16197625,  436967.10645861,
        465925.45832646,  505004.49933871,  395417.47789606,
        259735.6012932 ,  457955.58609422,  505528.8354064 ,
        935546.61058292,  687535.98295554,  293946.77848584,
        679485.40696815,  606662.50768113,  572315.67392641,
        559193.75240531,  284042.30788167,  421554.07142412,
        987894.76128244,  534542.69326304,  496967.34547252,
        708309.78282986,  497855.07765951,  348906.28324493,
        700036.34023872,  658842.11610655,  748916.12113993,
        456889.81410119,  234822.88673158,  325880.15192843,
        851023.16354159,  501522.57148188,  322507.58413751,
        641323.77132254,  301352.43784723,  441017.64000707,
        746023.50228475,  365920.46782963,  304228.47154897,
        389916.23620543,  343340.19836801,  314416.73184858,
        601070.4470824 ,  705494.5400178 ,  385990.82076294,
        461972.57563935,  543850.2186172 ,  367330.24783676,
        960769.13665912,  864654.99770492,  231267.01245933,
        306923.39689156,  232045.74313022,  278413.76939091,
        392767.17195687,  701866.06649057,  623131.04869595,
        314645.38190691,  786577.65106371,  663010.1026747 ,
       1270930.54865248,  670107.35960871,  379278.47204418,
        231100.63019577,  352938.41648111,  949097.3174305 ,
        373447.35087191,  659398.77552723,  526668.90586821,
        501432.44756054,  856792.43363339,  345942.77418899,
        644238.55828127,  756287.80862228,  220989.58670559,
        470507.17233942,  868878.09292764,  366359.5418329 ,
        721976.59018498,  832592.75176081,  318162.77937488,
        632858.00253209,  672631.143658  ,  345347.86338095,
        451682.75091097,  233551.30505418,  699192.38124247,
        347672.36386127,  385171.12437749, 1644039.87436903,
        705223.75857578,  359774.15078893,  618364.2732684 ,
        433957.37604346,  868717.71157958,  205625.91502121,
        230264.25777513,  666358.21480621,  437306.74681796,
       1491712.92837301,  813671.67666597,  881454.88755597,
        226799.09209913,  120172.73826379,  337651.98364342,
        625792.43692011,  157693.06323673,  594890.54687383,
        452088.94474126,  514947.8356932 ,  649541.45834168,
        545248.19732345,  311324.2350751 ,  847322.15821978,
        610735.68836131,  288175.32025383,  926072.28262022,
        476833.92678587,  567609.62922199,  277853.74553673,
        287020.96740137,  361860.6653395 ,  443776.41217053,
        374960.26990821,  726115.32331987,  670723.96766634,
        250671.12171245,  575575.54855167,  653359.48108807,
        591815.56316702,  400896.03656745,  347957.5981818 ,
        540941.3650168 ,  742280.53730754,  233041.12000286,
        376287.08149767,  271877.03713193,  452204.01514218,
        649865.41326084,  743367.95961856, 1228265.73128933,
        279001.57606059,  314397.72258865,  358860.67024657,
        513085.26422561,  516014.53472952,  556030.22381438,
        315671.46825346,  301937.19045199,  594495.9515823 ,
        445860.63069872,  465097.18331776,  352601.74715812,
        351736.87502353,  247028.58413393,  135464.05832306,
        441859.91737899,  367300.23062229,  354665.66784463,
       1333140.76464673,  217904.55858079,  801328.4643064 ,
        587377.85304759,  375343.59224041,  172703.07870031,
        468294.94761981,  243841.65503152,  341831.25454691,
        502044.83150028,  566184.41339698,  740984.88580626,
        362873.49868338,  296578.09776023,  248816.49812519,
       1119821.29792266,  698053.47784977,  266990.83348116,
        827698.45315562,  394504.55509451,  308170.79220704,
        350172.72755136,  597264.78726712,  872327.60382098,
        309642.9166667 ,  401626.79667179,  303959.0786053 ,
        552362.53882899,  750150.5939226 ,  454832.235592  ,
        290144.82881705,  796211.4814023 ,  569097.53989263,
       1075586.09150464,  246349.25235859,  241487.39462278,
        531415.59570119,  433234.03633689,  717085.60829999,
        402451.02586374,  570762.15605751,  865349.20016935,
        709865.04254679,  346481.64770366,  500266.08804781,
        363185.34172978,  648139.26400097,  505240.74172083,
        553268.08491052,  567497.69445371,  591744.39476661,
        214598.27427633,  252777.2441415 ,  428413.2798568 ,
        601595.97510257, 3741809.20885032, 1652931.67666683,
       1138388.98822626, 1007760.6705204 ,  480523.74616351,
       1084830.38355199,  268203.36080414,  477597.30821951,
        935377.65420073,  419153.45504799,  545823.40226698,
        284671.3960233 ,  441114.30234   ,  706776.26909152,
        445680.7220527 ,  382853.00753472,  287117.74679367,
        383331.51325569,  719066.30110857,  468338.41402264,
        296077.7731108 ,  641918.47444613,  373216.67983479,
        475656.68313901,  882005.78031822,  165765.72573608,
        488631.82408761,  720806.22664533,  418457.81187514,
       1297648.44065002,  269473.53084509,  324915.65386155,
        225700.30565944,  561906.21983757,  902892.73046776,
        310907.11473727,  546053.4166944 ,  817937.69764242,
        434813.80219966,  247453.7187962 ,  584666.52333413,
        159801.5135769 , 1139747.7611635 ,  397648.61349207,
        432353.63428226,  165698.9516104 ,  377421.71953371,
        615548.7238129 ,  423180.11181555,  677538.04671143,
        528502.40007825,  492744.89021942, 1171813.80237464,
        351381.46894451,  597935.97747064,  819926.42901931,
        764126.49031747,  632546.1716051 ,  524729.79100532,
        206430.43500706,  455856.38324473,  531290.13496555,
        465928.75298428,  302743.30302824,  579208.65242897,
        581588.33874505,  245312.8197025 ,  762269.06614206,
        400058.32123512,  486077.06445071,  459512.45620942,
        319241.36732722,  254188.25714159,  566385.21602455,
        248630.1052649 ,  586886.68860981,  393218.56868716,
        959066.53453247,  410713.33654838,  336740.0575161 ,
        265471.10881792,  382719.8726711 ,  241431.10204088,
        634034.04230612,  159506.91112488,  883207.74779583,
        532677.50029613,  604255.61194272,  476033.22542348,
        465569.00846058,  351258.12177984,  262939.62426205,
       1082079.41358748,  611618.00042819,  843007.78300123,
        372685.34581197,  903361.31425501,  578801.56114319,
        318209.40176294,  612594.53022626,  513207.23143246,
        950277.74356297,  337284.04543067,  659912.80065156,
        547489.8748498 ,  570662.57329315,  254379.40113274,
        823196.05552134,  429660.90722807,  276949.09415661,
        546689.22556338,  212252.66607401,  454011.84661134,
        597042.41080015,  662006.66717701,  509299.09334696,
        739710.57498762,  439776.15596343,  211475.50494528,
        197747.47749114,  288110.51973203,  670745.20885785,
        524478.45639558,  412228.01736264,  500635.97668608,
        501648.96196618,  560981.99373063,  184189.05793225,
        208988.17629534,  581558.00202637,  644844.74758913,
        266886.28606829,  238823.9611587 ,  406847.95247428,
        240456.1202627 ,  286849.35739353,  220969.25303379,
        660299.77038922, 1045915.6056379 , 1128620.07171113,
        618640.05621987,  840382.00673873,  764552.7667313 ,
        196777.96670371,  515247.95054896,  598079.29889521,
        381710.53759705,  718570.47881443,  617821.92150909,
        624432.57843355,  267570.8809813 ,  494055.22069719,
        303577.03684544,  614142.91990914,  198244.77208541,
       1366074.7244611 ,  278146.54503711, 1162994.98914952,
        502657.53874873, 1221470.67212617,  207236.97292759,
        806260.40987688,  331322.0039717 ,  289737.29851756,
        374307.72622182,  624407.310459  ,  654745.80525535,
       1341866.25915801,  357660.61298871,  496936.76780831,
        384276.24478979, 1081614.40524212,  716837.57845924,
        707081.47163485,  403403.02822371,  538541.09454406,
        724331.42430081,  215190.633049  ,  273397.68696745,
        356189.98059646,  582673.08869111,  379912.7874456 ,
        697526.47910028,  217288.70627648,  319209.83859004,
        199938.40108962,  689609.23329321,  561069.7168742 ,
        478883.00619456,  334711.12167804,  668991.88174195,
        373299.14198645,  345434.56925391,  252075.37129948,
        485301.55268071,  736107.31321598,  371373.76251045,
        432531.4540631 ,  434921.04769644,  272401.21680171,
        332323.71907338,  651298.28430796, 1098910.80611071,
        841706.20596048,  564600.87736239,  604729.50286628,
        419135.53740823,  394581.62547384,  377059.06343057,
        708022.95796606,  369998.78446843,  509550.10914249,
        284686.703795  ,  215653.46702106,  562256.04858156,
        284812.9048546 ,  848298.33900823,  162591.38679739,
        176069.44856477,  363154.94820909,  319101.9036804 ,
        628009.40471065,  280157.23638259,  898396.58369918,
        524419.48304515,  498409.14747027,  385520.13768411,
        872082.29296124,  559928.68768528,  240810.98606398,
        538999.67605604,  380752.60310612,  114240.96935475,
        444342.21520919,  222706.34466041,  636116.03061907,
        311664.09340711,  738277.53695625,  415342.94188061,
        778751.48515264,  321267.07974298,  433552.59929315,
        694501.25765208,  480459.07966842,  164639.28276508,
        579971.58113522,  338419.48838866,  652110.21668346,
        432882.76334091,  463214.17767248,  416404.76019362,
        369687.80695385,  356525.68811445,  565685.30930397,
        224652.6293644 ,  298322.55541893, 1133865.69594523,
        685194.53604538, 2011029.1548836 ,  421088.9865996 ,
        684962.41626148,  475993.12149673,  765498.82233161,
        654775.23043809,  248136.98316193,  595603.37955874,
        709516.36762867,  874921.86741387,  724576.716549  ,
        121842.00064652,  249149.74977197,  215545.20239781,
        528892.41531498, 1218575.51133416,  536598.20879061,
        381064.37099664,  597647.8617528 ,  498742.40487791,
       1409728.31761795,  317534.57915902,  411205.97628144,
       1323466.11790844,  267403.34497021,  237712.51881706,
        599840.75320581,  620604.10922728,  366168.86975814,
        217214.00961104,  673910.11866882,  566556.1636168 ,
        410724.11691783,  261176.10388104,  259288.01202181,
        329281.34221938,  478864.08080086,  158582.45345622,
        613952.86609124,  806156.8042822 ,  770361.65860361,
        605210.0174616 ,  169189.80151472,  835740.0604011 ,
        262206.97452584,  620695.22191816,  768390.5423674 ,
        664659.22501716,  397232.42185108,  792986.83799513,
        637172.88063572, 1019057.91459624,  322363.06734643,
        658127.41579782, 1129109.13603983,  582570.96000551,
        571112.93544107,  363824.79099732,  472046.51004492,
        956920.67479265, 1046916.03472969,  593688.80453969,
        526907.26625721,  197540.61546062,  497802.7531919 ,
        725894.15894449,  649329.76118591,  467049.63183737,
        304711.8237285 ,  214256.40623911,  518719.5238687 ,
        698336.78253381,  772710.30563193,  286777.85220095,
        515261.54610215,  840740.24694924,  241220.06488602,
        177262.20624955,  526442.55028309,  528630.00923756,
       1264206.21903229,  587973.92131367,  232606.869882  ,
        495534.46728548,  333272.05561474,  567517.03472863,
       1007549.45836574,  992274.61551464,  318920.57032594,
        243279.93950147,  835024.80905801,  229338.52121365,
        570903.79919   ,  482579.39238174,  259082.39360701,
        626328.05652024,  445707.96670403,  694360.48628376,
        438157.29885384,  356093.14195536,  591581.97384834,
        454534.96325804,  570331.08862901,  822306.12597791,
        413680.04328969,  995690.60477311,  860333.35808884,
        462746.76425662,  901116.07915107,  966945.81579096,
        387246.78241725,  492598.78463938,  645751.54426425,
        444316.07880998,  330405.23956598,  518210.87089763,
        539707.91708301,  236311.59363254,  375395.57822164,
        298884.47115173,  441243.86977783,  751594.59706346,
        606596.25265225, 1116568.84179353,  572046.94057256,
        726150.95713145,  558999.25702308,  252055.28038738,
        518888.00271638,  237498.61728465,  182934.06387888,
        556568.04184948,  771000.48498835, 1055672.55671797,
        383452.26197295,  780426.43954173,  950877.3588805 ,
        657176.39793564,  504861.85830718,  202445.44722695,
        464442.79775349,  615836.79898997, 1309781.23032706,
        341397.0450263 ,  378959.24947849,  266662.96097594,
        186743.47381672,  406576.46221509,  208187.23354074,
        464018.21217068,  524251.51446799,  406027.59123401,
        446061.43367611,  719966.52024282,  707815.51998671,
       1232077.20197303,  298852.15798687,  443078.64194214,
        204463.53239166,  479101.86135927,  291122.52128763,
        434834.14067773,  726235.5692014 ,  841815.78890648,
        742086.42050357,  621650.51697794,  616878.60072301,
        699024.91019049,  693097.70995122, 1096456.77640843,
        325063.55857969,  336545.61123841,  731797.05072165,
        406393.18456656,  582198.34117586,  507351.91795766,
        431452.69296364,  399824.66812147,  450349.92028955,
        554863.63140193,  357189.84385943,  316851.13996839,
         99811.59372748,  521173.57901119,  733539.20910154,
        485500.33600986,  354305.84425991,  415590.54356011,
        632203.62999032,  508865.4531386 ,  198841.38001604,
        564008.15808657,  538513.30324347, 1011046.02454389,
        570583.40410725,  825299.85815284,  748544.91137574,
        409329.45592612,  413326.31678828,  504445.16231936,
        337790.03267866,  746780.3910263 ,  291398.63035164,
        238624.07087432,  527582.38327103,  427421.8232507 ,
        570430.46458704,  564581.35029009,  280605.06634981,
        390242.98395109, 1012015.57633007,  496611.13092035,
        249316.45378007,  714920.59049209,  766424.42474156,
        360893.24925381,  427205.64544713,  441080.88302992,
        350113.87303479,  513559.39700904,  738285.62452445,
        253161.82779573,  586804.75688829,  420106.32518024,
        461067.22184582,  625644.66526404,  751041.34509188,
        402573.69757523,  569275.39204734,  856681.84685385,
        449106.65881744,  405835.8598812 ,  537331.57640833,
        456780.04160969,  485673.92831615,  505771.82536795,
        222387.53952192, 1059095.06873885,  336938.04447945,
       1068894.35855135,  565084.49023341,  695084.79330346,
        472281.97116905,  319337.49863625,  327741.6519782 ,
        512624.60625568,  619785.55383215,  634281.86247103,
        491500.65457837,  347656.62896743,  530744.33286467,
        263195.96630725,  590436.34056296,  534105.89288327,
        354655.05710018,  573053.42823801,  722431.74103477,
        503411.47875845,  598185.66262646,  433077.89995089,
        475447.63577599,  392363.62300443,  522225.95956129,
        472077.9609268 ,  431825.801744  ,  481597.82528172,
        438996.49035748,  801345.16630816,  280305.11541092,
        252374.16236073,  540951.39345491,  885886.54374323,
        716380.83261306,  212042.14814547,  335071.23589142,
        447521.70129516,  232700.81185388,  390710.79228661,
       1455734.3354178 ,  397155.64710061,  265813.85034741,
        390527.29521241,  677488.12626155,  276526.24613324,
        765590.54221667,  576454.26971364, 1033675.70325309,
        653747.87129667,  258315.27038093,  436281.36317748,
        780993.66481038,  781581.60464037,  437421.51840646,
        431690.84024093,  800956.00317171,  297898.88127642,
        751513.74731081,  717003.20183828,  423666.86692228,
        755855.739148  ,  528503.95679554,  411522.25130244,
        518192.24768169,  639716.17676288,  479089.72688958,
       1007759.87300784, 1171233.81296259,  811058.07370581,
        463272.36272728,  479321.05695906, 1821105.12188948,
        565726.28650588, 1443857.75410923,  937645.76611807,
        701791.56210526,  632253.7393099 ,  253639.61942827,
        306291.04307931,  402756.99813272,  376540.35064484,
        396943.03051921,  229875.86927484,  857915.83922467,
        153539.7044928 ,  580824.72800557,  743559.25633354,
        474534.3600954 ,  378623.18476724,  432558.80911272,
        692425.16838995,  455821.05516422,  164641.61902439,
        658613.20637142,  295384.69816172,  353001.27049791,
        394009.285446  ,  304805.95332614,  633469.72966568,
        195698.54050121,  312503.70259485,  526469.59621589,
        518240.9708242 ,  529252.99971995,  669621.26549903,
        188269.38338199,  532016.72273121,  305268.55789482,
        429002.20564426,  424154.66628042,  205774.29794171,
        652680.68942629,  545299.79746642])

In [19]:
# model accuracy on test data 
y_pred=model.predict(x_test)
r2_score(y_test,y_pred)

0.033045043902085514

In [20]:
# model accuracy on train data 
y_pred2=model.predict(x_train)
r2_score(y_train,y_pred2)

0.5493658609836938

In [21]:
# model selection
tree=DecisionTreeRegressor(max_depth=7,random_state=42)  # decision initialize
random=RandomForestRegressor(n_estimators=100,max_depth=7,random_state=42) # random forest

In [22]:
# model traning using decision tree 
tree.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=7, random_state=42)

In [23]:
# accuracy on test data 
y_pred=tree.predict(x_test)
r2_score(y_test,y_pred)

0.025982615394391395

In [24]:
# model traing using random forest
random.fit(x_train,y_train)

RandomForestRegressor(max_depth=7, random_state=42)

In [25]:
# accuracy 
y_pred=random.predict(x_test)
r2_score(y_test,y_pred)

0.041116956049891185

## PREDECTIVE MODEL ==

In [26]:
## BY RANDOM FOREST REGRESSION --->

In [27]:
# bedrooms	bathrooms	sqft_living	sqft_lot	floors	waterfront	view	condition	sqft_above	sqft_basement	yr_built	yr_renovated	street	city	statezip	country
date=int(input("Enter date ---> :"))
bedrooms=int(input("Enter no. of bedrooms -->:"))
bathrooms=int(input("Enter the no. of bathrooms --->:"))
sqft_living=int(input("Enter sqft_living of house  --> :"))
sqft_lot=int(input("Enter sqft_lot of house ---> :"))
floors=int(input("Enter the floors of house --->:"))
waterfront=int(input("Enter waterfront of house ---> (0 for NO, 1 for yes ):"))
view=int(input ("Enter the view of house --> (0:4):"))
condition=int(input("Enter the condition of house  -->(1-5):"))
sqft_above=int(input("Enter the sqft_above  --> :"))
sqft_basement=int(input("Enter the sqft_basement --->:"))
yr_built=int(input("Enter the yr_built --> (e.g., 1995) :"))
yr_renovated=int(input("Enter the yr_renovated ---> (0 if never):"))
street=int(input("Enter street -->:"))
city=int(input("Enter city -->:"))
statezip=int(input("Enter the satezip --->:"))
country=int(input("Enter the country ---> :"))
pred=model.predict([[date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country]])
print("Selling price of house is:",pred)

Enter date ---> : 26
Enter no. of bedrooms -->: 5
Enter the no. of bathrooms --->: 3
Enter sqft_living of house  --> : 600
Enter sqft_lot of house ---> : 2
Enter the floors of house --->: 1
Enter waterfront of house ---> (0 for NO, 1 for yes ): 1
Enter the view of house --> (0:4): 2
Enter the condition of house  -->(1-5): 4
Enter the sqft_above  --> : 10
Enter the sqft_basement --->: 900
Enter the yr_built --> (e.g., 1995) : 2000
Enter the yr_renovated ---> (0 if never): 2024
Enter street -->: 6
Enter city -->: 126
Enter the satezip --->: 55
Enter the country ---> : 0

Selling price of house is: [2208509.09383637]

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(